### PR TITLE
Rmeove sub operations from operations

### LINKED ISSUE #47: Remove sub operation calls
After a discussion with @mattgmarcus, we have decided that operations should not depend on other operations (save the example of required full updates on QBO).  The idea here is that we would do the following:

1. Remove Upserts: This functionality can be replicated by the user of the lib (e.g. perform a `Find` to determine if `Create` or `Update` is necessary).  This logic could also me moved to the `Coordinator` or a similar utility class.
2. Remove "sub operation" calls to `Create` or `Update` from all `Create` operations.  We are doing this first as only `Create` will be used for MVP.
3. Remove "sub operation" calls to `Create` or `Update` from all `Update` operations.

The motivations here are the following:

A. As written, there will be unexpected results.  For example, if someone calls the `Expense::Create` operation directly, it currently will attempt to call `Vendor::Upsert`.  There is no way to error if the supplied vendor resource no longer exists in the ledger (which is a use case).
B. Reduce complexity (e.g. needing to think through/handle something like #44).

### PR DESCRIPTION
**Pull request by ryanwjackson**
Fix #47 

This depends on #52 being merged first and the base being changed to `master`.

### CODE REVIEW

File: lib/ledger_sync/adaptors/quickbooks_online/operation.rb [hunk 1]
```diff
@@ -0,0 +1,30 @@
+# frozen_string_literal: true
+
+module LedgerSync
+  module Adaptors
+    module QuickBooksOnline
+      module Operation
+        TYPES = %i[create find update upsert].freeze
```
Comment (mattgmarcus) [inline lib/ledger_sync/adaptors/quickbooks_online/operation.rb]: We're removing upsert aren't we?

Comment (ryanwjackson) [reply lib/ledger_sync/adaptors/quickbooks_online/operation.rb]: Not yet.
